app:
  name: skeleton
server:
  port: 8000
logging:
  level: debug
database:
  master:
    driver: postgres
    host: 192.168.18.224
    port: 5432
    username: postgres
    password:
    name: chi
    sslmode: disable
bcrypt:
  cost: 10
jwt:
  secret: development_secret_key
  algorithm: HS256
  access:
    expiration_minutes: 43200
  refresh:
    expiration_minutes: 43200
timezone:
  location: Asia/Jakarta
