server:
  port: 8000
logging:
  level: debug
database:
  master:
    driver: postgres
    host: localhost
    port: 5432
    username: dev_user
    password: dev_password
    name: dev_db
    sslmode: disable
bcrypt:
  cost: 10
jwt:
  secret: development_secret_key
  algorithm: HS256
  access:
    expiration_minutes: 43200
  refresh:
    expiration_minutes: 43200
timezone:
  location: Asia/Jakarta
