app:
  name: skeleton
server:
  port: 8080
logging:
  level: info
database:
  master:
    driver: postgres
    host: localhost
    port: 5432
    username: prod_user
    password: prod_password
    name: prod_db
    sslmode: disable
bcrypt:
  cost: 12
hmac:
  token_secret: development_hmac_secret_key
jwt:
  secret: production_secret_key
  algorithm: HS256
  access:
    expiration_minutes: 15
  refresh:
    expiration_minutes: 43200
timezone:
  location: Asia/Jakarta
